name: Rapport om hendelse
description: Rapporter en hendelse
title: "INCIDENT [YYMMDD] - [Tittel]"
labels: ["Incident"]
type: "Task"
body:
  - type: markdown
    attributes:
      value: |
        Legg inn en kort beskrivende tittel på hva problemet er i feltet [Tittel] og tidspunkt for hendelsen på formatet YYMMDD (f.eks. 241231)
  - type: textarea
    id: beskrivelse
    attributes:
      label: Beskrivelse
      description: Gi en kort beskrivelse av hva som har skjedd
      placeholder: Eksempel - Klokken 14:30 kom det melding fra X om at Y hadde stoppet opp. Jeg har ikke klart å finne ut hva som er galt og trenger hjelp til dette.
    validations:
      required: true
  - type: textarea
    id: Varsling
    attributes:
      label: Varsling?
      placeholder: Er det behov for varsling? Kom gjerne med forslag til ønsket varslingstekst
